/* Generated By:JavaCC: Do not edit this line. CLIPSParserConstants.java */
package org.jamocha.parser.clips;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CLIPSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_TEXT = 7;
  /** RegularExpression Id. */
  int END_COMMENT = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 11;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 12;
  /** RegularExpression Id. */
  int EXPONENT = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int BIND = 15;
  /** RegularExpression Id. */
  int BIND2 = 16;
  /** RegularExpression Id. */
  int BIND3 = 17;
  /** RegularExpression Id. */
  int BIND4 = 18;
  /** RegularExpression Id. */
  int BIND5 = 19;
  /** RegularExpression Id. */
  int BINDING = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int AGGREGATE = 22;
  /** RegularExpression Id. */
  int ASSERT = 23;
  /** RegularExpression Id. */
  int ASSERTTEMPORAL = 24;
  /** RegularExpression Id. */
  int AUTOFOCUS = 25;
  /** RegularExpression Id. */
  int ALLOWEDVALUES = 26;
  /** RegularExpression Id. */
  int CHAININGDIRECTION = 27;
  /** RegularExpression Id. */
  int COMMAND = 28;
  /** RegularExpression Id. */
  int CUBEQUERY = 29;
  /** RegularExpression Id. */
  int DECLARE = 30;
  /** RegularExpression Id. */
  int DEFCLASS = 31;
  /** RegularExpression Id. */
  int DEFCUBE = 32;
  /** RegularExpression Id. */
  int DEFFACT = 33;
  /** RegularExpression Id. */
  int DEFFUNCTION = 34;
  /** RegularExpression Id. */
  int DEFMODULE = 35;
  /** RegularExpression Id. */
  int DEFRULE = 36;
  /** RegularExpression Id. */
  int DEFQUERY = 37;
  /** RegularExpression Id. */
  int DEFGRAPHQUERY = 38;
  /** RegularExpression Id. */
  int DEFTEMPLATE = 39;
  /** RegularExpression Id. */
  int DESCRIBECLASS = 40;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 41;
  /** RegularExpression Id. */
  int DOUBLE = 42;
  /** RegularExpression Id. */
  int EXISTS = 43;
  /** RegularExpression Id. */
  int EFFECTIVE = 44;
  /** RegularExpression Id. */
  int EXPIRATION = 45;
  /** RegularExpression Id. */
  int FACTINDEX = 46;
  /** RegularExpression Id. */
  int FLOAT = 47;
  /** RegularExpression Id. */
  int HASHEDMEMORY = 48;
  /** RegularExpression Id. */
  int INTEGER = 49;
  /** RegularExpression Id. */
  int INTERVALTIME = 50;
  /** RegularExpression Id. */
  int LOGICAL = 51;
  /** RegularExpression Id. */
  int LONG = 52;
  /** RegularExpression Id. */
  int MODIFY = 53;
  /** RegularExpression Id. */
  int MULTISLOT = 54;
  /** RegularExpression Id. */
  int MULTIPLECE = 55;
  /** RegularExpression Id. */
  int NOAGENDA = 56;
  /** RegularExpression Id. */
  int NOLOOP = 57;
  /** RegularExpression Id. */
  int NUMBER = 58;
  /** RegularExpression Id. */
  int NOTCE = 59;
  /** RegularExpression Id. */
  int ONLYCE = 60;
  /** RegularExpression Id. */
  int REMEMBERALPHA = 61;
  /** RegularExpression Id. */
  int RETRACT = 62;
  /** RegularExpression Id. */
  int RULEVERSION = 63;
  /** RegularExpression Id. */
  int RELATIVETIME = 64;
  /** RegularExpression Id. */
  int SALIENCE = 65;
  /** RegularExpression Id. */
  int SEND = 66;
  /** RegularExpression Id. */
  int SHORT = 67;
  /** RegularExpression Id. */
  int SLOT = 68;
  /** RegularExpression Id. */
  int STRING = 69;
  /** RegularExpression Id. */
  int SYMBOL = 70;
  /** RegularExpression Id. */
  int TEMPORALACTIVATION = 71;
  /** RegularExpression Id. */
  int TEMPORAL = 72;
  /** RegularExpression Id. */
  int TEST = 73;
  /** RegularExpression Id. */
  int TRUE = 74;
  /** RegularExpression Id. */
  int TRUE2 = 75;
  /** RegularExpression Id. */
  int TYPEDEF = 76;
  /** RegularExpression Id. */
  int FALSE = 77;
  /** RegularExpression Id. */
  int FALSE2 = 78;
  /** RegularExpression Id. */
  int NIL = 79;
  /** RegularExpression Id. */
  int ARROW = 80;
  /** RegularExpression Id. */
  int LEFT_ARROW = 81;
  /** RegularExpression Id. */
  int ASSIGN = 82;
  /** RegularExpression Id. */
  int SEMICOLON = 83;
  /** RegularExpression Id. */
  int PLUS = 84;
  /** RegularExpression Id. */
  int MINUS = 85;
  /** RegularExpression Id. */
  int MULTIPLY = 86;
  /** RegularExpression Id. */
  int DIVIDE = 87;
  /** RegularExpression Id. */
  int GT1 = 88;
  /** RegularExpression Id. */
  int LT1 = 89;
  /** RegularExpression Id. */
  int EQ1 = 90;
  /** RegularExpression Id. */
  int EQ2 = 91;
  /** RegularExpression Id. */
  int LE1 = 92;
  /** RegularExpression Id. */
  int GE1 = 93;
  /** RegularExpression Id. */
  int NE1 = 94;
  /** RegularExpression Id. */
  int NE2 = 95;
  /** RegularExpression Id. */
  int AND1 = 96;
  /** RegularExpression Id. */
  int AND2 = 97;
  /** RegularExpression Id. */
  int OR1 = 98;
  /** RegularExpression Id. */
  int OR2 = 99;
  /** RegularExpression Id. */
  int TILDA = 100;
  /** RegularExpression Id. */
  int IDENTIFIER = 101;
  /** RegularExpression Id. */
  int LETTER = 102;
  /** RegularExpression Id. */
  int DIGIT = 103;
  /** RegularExpression Id. */
  int PATH_LITERAL = 104;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";;\"",
    "<token of kind 6>",
    "<COMMENT_TEXT>",
    "<END_COMMENT>",
    "\"(\"",
    "\")\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<BIND>",
    "<BIND2>",
    "<BIND3>",
    "<BIND4>",
    "<BIND5>",
    "\"bind\"",
    "\"BOOLEAN\"",
    "\"aggregate\"",
    "\"assert\"",
    "\"assert-temporal\"",
    "\"auto-focus\"",
    "\"allowed-values\"",
    "\"chaining-direction\"",
    "\"command\"",
    "\"cubequery\"",
    "\"declare\"",
    "\"defclass\"",
    "\"defcube\"",
    "\"deffact\"",
    "\"deffunction\"",
    "\"defmodule\"",
    "\"defrule\"",
    "\"defquery\"",
    "\"defgraphquery\"",
    "\"deftemplate\"",
    "\"describe-class\"",
    "\"default\"",
    "\"DOUBLE\"",
    "\"exists\"",
    "\"effective-date\"",
    "\"expiration-date\"",
    "\"fact-index\"",
    "\"FLOAT\"",
    "\"hashed-memory\"",
    "\"INTEGER\"",
    "\"interval-time\"",
    "\"logical\"",
    "\"LONG\"",
    "\"modify\"",
    "\"multislot\"",
    "\"multiple\"",
    "\"no-agenda\"",
    "\"no-loop\"",
    "\"NUMBER\"",
    "\"not\"",
    "\"only\"",
    "\"remember-alpha\"",
    "\"retract\"",
    "\"rule-version\"",
    "\"relative-time\"",
    "\"salience\"",
    "\"send\"",
    "\"SHORT\"",
    "\"slot\"",
    "\"STRING\"",
    "\"symbol\"",
    "\"temporal-activation\"",
    "\"temporal\"",
    "\"test\"",
    "\"TRUE\"",
    "\"true\"",
    "\"type\"",
    "\"FALSE\"",
    "\"false\"",
    "\"nil\"",
    "\"=>\"",
    "\"<<=\"",
    "\"<-\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"eq\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"and\"",
    "\"&\"",
    "\"or\"",
    "\"|\"",
    "\"~\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<PATH_LITERAL>",
  };

}
